# -*- mode: ruby -*-
# vi: set ft=ruby :

# Centos 7 Spark Slave 1 Vagrant File

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define "spark-slave-1" do |host|
    host.vm.hostname = "spark-slave-1"
    host.vm.provider :virtualbox do |vb|
      vb.name = host.vm.hostname.to_s
	  vb.gui = false
      vb.memory = "1024"
    end
  end

  config.vm.network "private_network", ip: "192.168.50.12",virtualbox__intnet: true

  config.vm.provision "file", source: "spark.service", destination: "~/spark.service"
  config.vm.provision "file", source: "hosts", destination: "~/hosts"

  config.vm.provision "shell", path: "setup.sh"

end