Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define "spark-master" do |host|
    host.vm.hostname = "spark-master"
    host.vm.provider :virtualbox do |vb|
	  vb.name = host.vm.hostname.to_s
	  vb.gui = false
      vb.memory = "1024"
    end
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8881, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.50.11",virtualbox__intnet: true
#  config.vm.network "forwarded_port", guest: 7077, host: 7770, host_ip: "127.0.0.1"
# config.vm.network "forwarded_port", guest: 6066, host: 6660, host_ip: "127.0.0.1"

  config.vm.provision "shell", path: "setup.sh"
#  config.vm.provision "file", source: "~/spark.service", destination: "/etc/systemd/system/spark.service"
end